// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qltmedibztziaduyesqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdG1lZGlienR6aWFkdXllc3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NjY4OTgsImV4cCI6MjA1NjM0Mjg5OH0.yMbuaJAHNWWFws3NshX69x7e3ARcI8AYRaNv6gVdg3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);